app:
  name: ui
  image:
    repository: onecx/onecx-document-management-ui
  routing:
    enabled: true
    path: /mfe/onecxDocumentManagementUi/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxDocumentManagementUiModule
          description: OneCX OnecxDocumentManagementUi Module
          note: OneCX OnecxDocumentManagementUi UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-document-management-ui
          tagName: onecx-document-management-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          DOCUMENT:
            READ: Read documents
            WRITE: Write document data
            DELETE: Delete document data
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-document-management-ui
